export enum AwsSetting {
  AWS_PROFILE_BUCKET_NAME = 'AWS_PROFILE_BUCKET_NAME',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
}
