export enum EnvEnum {
  TEST_MAILER_EMAIL = 'TEST_MAILER_EMAIL',
  TEST_MAILER_PASS = 'TEST_MAILER_PASS',
  MAILER_SUBJECT = 'MAILER_SUBJECT',
  FRONTEND_CONFIRM_EMAIL_LINK = 'FRONTEND_CONFIRM_EMAIL_LINK',
  JWT_SECRET = 'JWT_SECRET',
  JWT_TOKEN_EXPIRATION_TIME = 'JWT_TOKEN_EXPIRATION_TIME',
  FRONTEND_PASSWORD_RECOVERY_LINK = 'FRONTEND_PASSWORD_RECOVERY_LINK',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  RECAPTCHA_SECRET = 'RECAPTCHA_SECRET'
}
