export enum EnvEnum {
  TEST_MAILER_EMAIL = 'TEST_MAILER_EMAIL',
  TEST_MAILER_PASS = 'TEST_MAILER_PASS',
  MAILER_SUBJECT = 'MAILER_SUBJECT',
  FRONTEND_CONFIRM_EMAIL_LINK = 'FRONTEND_CONFIRM_EMAIL_LINK'
}
