name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - '*'
    types: [opened, edited, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run tests
        run: yarn test:e2e

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build
